AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  KodoStatHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/events/statEvent.handler
      Runtime: nodejs8.10
      Events:
        KodoStatEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - KodoStatQueue
              - Arn
            BatchSize: 10
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Resource:
            Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/KodoStatTable
      CodeUri: s3://kodo-lambda/6bf327148817662ac1f0cffcf8b62792
  KodoStatCalculationHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/calculations/eventCalculation.handler
      Runtime: nodejs8.10
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::GetAtt:
              - KodoStatStore
              - StreamArn
            BatchSize: 1000
            StartingPosition: TRIM_HORIZON
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Resource:
            Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/KodoCalculationTable
      CodeUri: s3://kodo-lambda/6bf327148817662ac1f0cffcf8b62792
  KodoStatQueue:
    Type: AWS::SQS::Queue
  KodoStatQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: KodoStatQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - KodoStatQueue
            - Arn
  KodoStatApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: KodoStatApi
      EndpointConfiguration: REGIONAL
      StageName: v1
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1'
          title: kodo
        basePath: /production
        schemes:
        - https
        paths:
          /v1/send:
            get:
              produces:
              - application/json
              parameters:
              - name: MessageBody
                in: query
                required: true
                type: string
              responses:
                '200':
                  description: 200 response
                  schema:
                    $ref: '#/definitions/Empty'
              security:
              - api_key: []
              x-amazon-apigateway-integration:
                credentials:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/kodo-apigateway
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:sqs:path/${KodoStatQueue.QueueName}
                responses:
                  default:
                    statusCode: '200'
                requestParameters:
                  integration.request.querystring.MessageBody: method.request.querystring.MessageBody
                  integration.request.querystring.Action: '''SendMessage'''
                  integration.request.header.Content-Type: '''application/json'''
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws
        definitions:
          Empty:
            type: object
            title: Empty Schema
  KodoStatStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KodoStatTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  KodoCalculationStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KodoCalculationTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
